#!/usr/bin/env python3
# Imports
from colorama import Back, Fore
from requests.exceptions import RequestException
import argparse
import os
import pyfiglet
import requests
import socket
import sys
from termcolor import colored

# Specify HTTP_CODES (More will be added for better enumeration)

HTTP_CODES = [200, 301, 302, 401, 403]

# ASCII Banner

ascii_banner = pyfiglet.figlet_format("THOOL")
colored_banner = colored(ascii_banner, color='magenta', attrs=['bold'])
print(colored_banner)

# Adding Arguments with argparse

parser = argparse.ArgumentParser(description="Enumerating Target Domain")

parser.add_argument("-u", "--url",
                    help="Target URL (example.com or https://example.com)")

parser.add_argument("-t", "--target",
                    help="Target IP")

parser.add_argument("-dir", "--directory_enum",
                    action="store_true",
                    help="Enable directory enumeration")

parser.add_argument("-sub", "--subdomain_enum",
                    action="store_true",
                    help="Enable subdomain enumeration")

parser.add_argument("-port", "--port_scanning",
                    action='store_true',
                    help="Enable port scanning")

parser.add_argument("-a", "--every_script",
                    action="store_true",
                    help="Run every enumeration script")

parser.add_argument("-w", "--wordlist",
                    help="Path to wordlist")

args = parser.parse_args()


# Normalising URL
if args.url:
    base_url = args.url
    if not base_url.startswith(("http://", "https://")):
        base_url = "http://" + base_url

# Setting the target IP 
target_ip = args.target

# Function for Port Scanning
def port_scan():
    open_ports = []
    closed_ports = []
    filtered_ports = []
    for i in range(1, 1001):
        with socket.socket() as s:
            s.settimeout(1)
            try:
                s.connect((target_ip, i))
                open_ports.append(i)
            except ConnectionRefusedError:
                closed_ports.append(i)
            except ConnectionError:
                continue
            except TimeoutError:
                filtered_ports.append(i)
            except OSError as e:
                sys.exit(f"[-] Exiting Program: {e}")


    len_closed = len(closed_ports)
    len_open = len(open_ports)
    print(Fore.CYAN + f"PORT{' ' * 20}STATUS\n{'-' * 80}")
    for port in open_ports:
        print(Fore.GREEN + f"{port}{' ' * 20}OPEN\n")
    for port in filtered_ports:
        print(Fore.YELLOW + f"{port}{' ' * 20}FILTERED\n")
    print(Fore.CYAN + f"[*] Found {len_closed + len_open} ports")
    print(Fore.CYAN + f"[*] Scan complete\n{'-' * 80}")


# Function for Subdomain enumeration

def sub_enum():
    print(Fore.CYAN + f'[*] Starting Subdomain Enumeration\n{'-' * 80}')
    if not args.wordlist:
        sys.exit(Fore.RED + "[-] -w/--wordlist is required for subdomain scanning.")

    try:
        with open(args.wordlist, "r") as wordlist:
            print(Fore.CYAN + f"[*] Opening wordlist at: {args.wordlist}")
            subs = []
            for sub in wordlist:
                sub = sub.strip()

                target = base_url.replace("://", f"://{sub}.")

                try:
                    response = requests.get(target, timeout=5)

                    if response.status_code in HTTP_CODES:
                        print(Fore.GREEN + f"[+] Found: {target} ({response.status_code})")
                        subs.append(sub)

                except RequestException:
                    pass
            print(Fore.CYAN + f"[*] Found {len(subs)} Subdomains for {args.url}\n\n")

    except FileNotFoundError:
        sys.exit(Fore.RED + f"[-] Wordlist not found at: {args.wordlist}")

# Function for Directory enumeration

def dir_enum():
    print(Fore.CYAN + f"[*] Starting Directory Enumeration\n{'-' * 80}")
    if not args.wordlist:
        sys.exit(Fore.RED + "[-] -w/--wordlist is required for directory scanning.")

    try:
        with open(args.wordlist, "r") as wordlist:
            print(Fore.CYAN + "[*] Opening wordlist at: ", args.wordlist)
            dirs = []
            for directory in wordlist:
                directory = directory.strip()

                try:
                    response = requests.get(
                        f"{base_url}/{directory}",
                        timeout=5
                    )

                    if response.status_code in HTTP_CODES:
                        print(Fore.GREEN + f"[+] Found: /{directory} ({response.status_code})")
                        dirs.append(directory)

                except RequestException:
                    pass
             
            print(Fore.CYAN + f"[*] Found {len(dirs)} directories for {args.url}\n\n")

    except FileNotFoundError:
        sys.exit(Fore.RED + f"[-] Wordlist not found at: {args.wordlist}")



# Choose atleast one scan type
if not (args.directory_enum or
        args.subdomain_enum or
        args.port_scanning or
        args.every_script):
    sys.exit(Fore.RED + "[-] You need to specify at least one scan option.")

# Checking if either an URL or IP has been passed
if not args.url and not args.target:
    sys.exit(Fore.RED + "[-] Specify an IP or URL")

# Checking if two targets have been passed
if args.url and args.target:
    sys.exit(Fore.RED + "[-] Specify only one target")



# Checking if an IP has been passed when port scanning
if args.port_scanning and not args.target:
    sys.exit(Fore.RED + "[-] You need to specify an IP for Port Scanning")

if args.every_script:
    dir_enum()
    sub_enum()
    port_scan()

# Run the script that the user wants
# -dir/--directory_scanning for directory enumeration | -sub/--subdomain_scanning for subdomain enumeration | -p/--port_scanning for Port Scanning
else:
    if args.directory_enum:
        dir_enum()

    if args.subdomain_enum:
        sub_enum()

    if args.port_scanning:
        port_scan()










